on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master

name: gendata

jobs:
  gendata:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_OPENPHARMA }}
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'

      - uses: r-lib/actions/setup-pandoc@master
      
      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Deploy data
        run: |
          Rscript create_data.R

      - name: Install dependencies
        run: |
          rmarkdown::render("index.Rmd")
          dir.create("build")
          file.copy(from = "index.html", to = "build/index.html")
        shell: Rscript {0}
        
      - name: Deploy site 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.