on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - develop

name: testing

jobs:
  testing:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GH_OPENPHARMA }}
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: 'release'

      - uses: r-lib/actions/setup-pandoc@master
      
      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Snakemake # python3 -m pip install --upgrade networkx pygraphvis
        run: |
          python3 -m pip install snakemake


      - name: Build
        run: |
          snakemake -j2  -F all
          mkdir build
          cp index.html ./build
        
